### PR TITLE
Remove this package from Sublime Package control

### PR DESCRIPTION
**Pull request by samvasko**
Hey I was using your package for Vala on Sublime. But recently I found [this one](https://github.com/technosophos/Vala-TMBundle) which is now on Package Control too. And I must say it has all the things! Proper colors, symbols and all. Therefore I would really appreciate if you could remove yours from package control to avoid confusion and bring better Vala experience for all. 

If you are too busy or whatever I can surely do it for you. Thanks for the work!
_(I am making pull request b/c the issues are disabled and I cant find your email, sorry)_

### CODE REVIEW

**Comment by keidaa** [comment]
Hmm, I never added this to the package control.

**Comment by samvasko** [comment]
Oh, well, sorry about that. I kinda assumed you did. I will check the blame.

**Comment by samvasko** [comment]
It looks like it was @Chipcius.

**Comment by Chipcius** [comment]
You are making a pull request to have this removed right? If you link to it here or send me a email I am glad to support it.

**Pull request closed without merging**
